enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGNUP_SCREEN = 'SIGNUP_SCREEN',
  PASSWORD_RESET = 'PASSWORD_RESET',
 CREATE_PASSWORD = 'CREATE_PASSWORD',
  OTP_SCREEN = 'OTP_SCREEN',
  RESTAURANT_DETAILS ='RESTAURANT_DETAILS',
ADD_RESTAURANT_DETAILS = 'ADD_RESTAURANT_DETAILS',
  BOTTOM_TAB ='BOTTOM_TAB',
  Add_DISH ='Add_DISH',
  DISH_LIST ='DISH_LIST',
  EditDish ='EditDish',

  // Tab Screens
  HOME_SCREEN='HOME_SCREEN',
  BOOKING_SCREEN = 'BOOKING_SCREEN',
  CART_STACK ='CART_STACK',
  PROFILE_STACK ='PROFILE_STACK',
  FAVORITE_SCREEN ='FAVORITE_SCREEN',
  PROFILE_SCREEN ='PROFILE_SCREEN',
  UpdateRestaurantDetails='UpdateRestaurantDetails',
  UpdateAddRestaurantDetails ='UpdateAddRestaurantDetails',
  MyOrder='MyOrder',
  TrackResToUser='TrackResToUser',

//Features screen



//profile
MY_ORDER = 'MY_ORDER',
TRACK_ORDER ='TRACK_ORDER',
PAYMENT_CARD ='PAYMENT_CARD',
ADDNEW_CARD = 'ADDNEW_CARD',
EDIT_PROFILE ='EDIT_PROFILE',
TERMS_CONDITIONS ='TERMS_CONDITIONS',
PRIVACY_POLICY ='PRIVACY_POLICY',
CHANGE_PASSWORD ='CHANGE_PASSWORD',
ADDRESS_SCREEN ='ADDRESS_SCREEN',
NOTIFICATION_SCREEN='NOTIFICATION_SCREEN',
ORDERS_DETAILS='ORDERS_DETAILS',
MY_DISHES_PROFILE='MY_DISHES_PROFILE'



  
}

export default ScreenNameEnum;
